In [1]:
import pandas as pd

# 2 Series

In [2]:
# 生成一个Series
ser_obj = pd.Series(range(10, 20))  # 默认索引是0-9
print(ser_obj)  # 打印输出会带有类型

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64


In [8]:
# 获取数据
print(ser_obj.values)
print(type(ser_obj.values))

# 获取索引
print(ser_obj.index)  # 内部自带类型--RangeIndex
ser_obj.dtype

[10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=10, step=1)


dtype('int64')

In [12]:
print(ser_obj[0])
ser_obj[9]
# 访问不存在索引下标会报keyerror

10


19

In [15]:
print(ser_obj * 2)  # 元素级乘法
print("-" * 100)
print(ser_obj > 15)  # 返回一个bool序列

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
----------------------------------------------------------------------------------------------------
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [20]:
# 字典变为series，索引是字典的key，value是字典的value，感受非默认索引
year_data = {2001: 17.8, 2005: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2)
print("-" * 100)
print(ser_obj2.index)
print("-" * 100)
print(ser_obj2[2001])
print("-" * 100)
print(ser_obj2.values)


2001    17.8
2005    20.1
2003    16.5
dtype: float64
----------------------------------------------------------------------------------------------------
Int64Index([2001, 2005, 2003], dtype='int64')
----------------------------------------------------------------------------------------------------
17.8
----------------------------------------------------------------------------------------------------
[17.8 20.1 16.5]


In [25]:
# 有点鸡肋的功能介绍
print(ser_obj2.name)  # series的名字
print(ser_obj2.index.name)  # 索引名字
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year'
print("-" * 100)
print(ser_obj2.head())

temp
year
----------------------------------------------------------------------------------------------------
year
2001    17.8
2005    20.1
2003    16.5
Name: temp, dtype: float64


# 3 DataFrame

In [35]:
import numpy as np

# 通过ndarray构建DataFrame
t = pd.DataFrame(np.arange(12).reshape(3, 4))  # 默认索引是0-2
print(t)
print("-" * 100)
print(t.loc[1])  # 单独把一行取出来，类型是series
print("-" * 100)
print(t.loc[:, 1])  # 单独取出一列

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
----------------------------------------------------------------------------------------------------
0    4
1    5
2    6
3    7
Name: 1, dtype: int32
----------------------------------------------------------------------------------------------------
0    1
1    5
2    9
Name: 1, dtype: int32


In [30]:
array = np.random.randn(7, 4)
print(array)
print("-" * 100)
df_obj = pd.DataFrame(array)
print(df_obj.head())  # 默认显示前5行
print("-" * 100)
print(df_obj)

[[-1.62958698 -0.94516892 -0.20722952 -1.3296112 ]
 [-0.0722564  -0.65083688 -0.02499286  1.41952532]
 [-0.11774451 -0.57208432  1.78963988  1.28040135]
 [ 1.13723424  0.21889934  0.01212634 -0.68993828]
 [-0.21649007 -0.71689887  0.78377189  0.40941247]
 [ 1.48861736 -1.64079488 -1.47943233  0.92851407]
 [-0.79581992 -1.46473642  1.1660837   0.10663436]]
----------------------------------------------------------------------------------------------------
          0         1         2         3
0 -1.629587 -0.945169 -0.207230 -1.329611
1 -0.072256 -0.650837 -0.024993  1.419525
2 -0.117745 -0.572084  1.789640  1.280401
3  1.137234  0.218899  0.012126 -0.689938
4 -0.216490 -0.716899  0.783772  0.409412
----------------------------------------------------------------------------------------------------
          0         1         2         3
0 -1.629587 -0.945169 -0.207230 -1.329611
1 -0.072256 -0.650837 -0.024993  1.419525
2 -0.117745 -0.572084  1.789640  1.280401
3  1.137234  0.21889

In [41]:
# 列表套字典 变df
d2 = [{"name": "xiaohong", "age": 22, "tel": 10010},
      {"name": "zhangsan", "tel": 10000},
      {"name": "xiaowang", "age": 23}]

df6 = pd.DataFrame(d2)
print(df6)  # 缺失值会用nan来填充
print(type(df6.values))
print("-" * 100)
print(df6.values)
print("-" * 100)
print(df6.index)
print("-" * 100)

       name   age      tel
0  xiaohong  22.0  10010.0
1  zhangsan   NaN  10000.0
2  xiaowang  23.0      NaN
<class 'numpy.ndarray'>
----------------------------------------------------------------------------------------------------
[['xiaohong' 22.0 10010.0]
 ['zhangsan' nan 10000.0]
 ['xiaowang' 23.0 nan]]
----------------------------------------------------------------------------------------------------
RangeIndex(start=0, stop=3, step=1)
----------------------------------------------------------------------------------------------------


In [42]:
pd.Series(1, index=list(range(3, 7)), dtype='float32')

3    1.0
4    1.0
5    1.0
6    1.0
dtype: float32

In [55]:
# df中不同列可以是不同的数据类型，同一列必须是一个数据类型
import pandas as pd
import numpy as np

dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)), dtype='float32'),
             'D': np.array([1, 2, 3, 4], dtype='int32'),
             'E': ["Python", "Java", "C++", "C"],
             'F': 'wangdao'}
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao


In [56]:
print(df_obj2.index)  # 行索引
print(df_obj2.columns)
df_obj2.dtypes  # 数据类型

Int64Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


A             int64
B    datetime64[ns]
C           float32
D             int32
E            object
F            object
dtype: object

In [62]:
# 感受日期，初始化df，设置行索引，列索引
dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print("-" * 100)
print(df.index)
print(type(df))
print(type(df.index))
print(type(df.columns))

                   A         B         C         D
2013-01-01 -0.401436 -0.229505  0.496768  0.332348
2013-01-02  1.165775 -0.634487  1.441721 -0.088407
2013-01-03  0.365227 -1.328374  1.010454  0.423365
2013-01-04  0.795187 -0.773066  1.289874 -0.327123
2013-01-05  1.449419 -0.110597 -0.844148 -0.482689
2013-01-06  0.671745  0.259030  0.680095  3.129528
----------------------------------------------------------------------------------------------------
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
<class 'pandas.core.indexes.base.Index'>


In [69]:
dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)), dtype='float32'),
             'D': np.array([1, 2, 3, 4], dtype='int32'),
             'E': ["Python", "Java", "C++", "C"],
             'F': 'wangdao'}
df_onj2 = pd.DataFrame(dict_data)
print(df_obj2)
print("-" * 100)
print(type(df_obj2))
print("-" * 100)
# pd中使用索引来取某一行或者列
print(df_obj2.loc[0])  # 取第一行
print("-" * 100)
print(df_obj2['B'])
print("-" * 100)
print(type(df_obj2['B']))

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
----------------------------------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
----------------------------------------------------------------------------------------------------
A                      1
B    2019-09-26 00:00:00
C                    1.0
D                      1
E                 Python
F                wangdao
Name: 0, dtype: object
----------------------------------------------------------------------------------------------------
0   2019-09-26
1   2019-09-26
2   2019-09-26
3   2019-09-26
Name: B, dtype: datetime64[ns]
----------------------------------------------------------------------------------------------------
<class 'pandas.core.series.Series'>


In [70]:
# 增加列数据，列名是自定义的
df_obj2['G'] = df_obj2['D'] + 4
print(df_obj2)

   A          B    C  D       E        F  G
0  1 2019-09-26  1.0  1  Python  wangdao  5
1  1 2019-09-26  1.0  2    Java  wangdao  6
2  1 2019-09-26  1.0  3     C++  wangdao  7
3  1 2019-09-26  1.0  4       C  wangdao  8


In [71]:
# 删除列数据
del (df_obj2['G'])
print(df_obj2)

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
