In [13]:
import numpy as np

# 列表转ndarray
list1 = [1, 2, 3, 4, 5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [4]:
oneArrary = np.array(list1)
print(oneArrary)
print(type(oneArrary))


[1 2 3 4 5]
<class 'numpy.ndarray'>


# ndarray与python原生list运算效率对比

In [8]:
import random
import time
import numpy as np

# 随机1亿个数据
a = [random.random() for i in range(10 ** 8)]
print("随机完毕")

随机完毕


In [9]:
b = np.array(a)  # 转换为ndarray
print("转为ndarray完毕")

转为ndarray完毕


In [10]:
# ndarray的计算效率要比python原生list高很多
start_time = time.time()
sum1 = sum(a)
end_time = time.time()
print("python原生list的计算时间:", end_time - start_time)

start_time = time.time()
sum2 = np.sum(b)
end_time = time.time()
print("ndarray的计算时间:", end_time - start_time)

python原生list的计算时间: 0.3562180995941162
ndarray的计算时间: 0.11182880401611328


In [12]:
print(type(range(10)))
t2 = np.array(range(10))
print(t2)
print(type(t2))

<class 'range'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [15]:
t3 = np.array(range(0, 10, 2))
print(t3)
print(type(t3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [17]:
# 二维列表转ndarray
import numpy as np

list2 = [[1, 2], [3, 4], [5, 6]]
twoArray = np.array(list2)
print(type(twoArray))
print(twoArray)
print(list2)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
[[1, 2], [3, 4], [5, 6]]


In [18]:
twoArray.tolist()  # ndarray转换为列表

[[1, 2], [3, 4], [5, 6]]

# 4.3 常用属性

In [21]:
# 看ndarray的各种属性
list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)

# 获取数组的维度
print(twoArray.ndim)

# 获取数组的形状
print(twoArray.shape)

# 获取数组的元素总数
print(twoArray.size)

# 获取数组的元素类型
print(twoArray.dtype)  # 默认int32,4字节,数据范围[-2147483648, 2147483647]


2
(3, 2)
6
int32


# 4.4 调整数组的形状

In [26]:
four = np.array([[1, 2, 3], [4, 5, 6]])
print(four)
print("-" * 100)
# ndarray也是可变数据类型
four1 = four
print(id(four1))
print("-" * 100)
four.shape = (3, 2)  # 改变数组的形状
print(four)
print(id(four))
print(id(four1))  # 数组的id不变
print("-" * 100)

# 返回一个新数组，reshape后id和之前的不一样
four2 = four.reshape(2, 3)
print(id(four))
print(id(four2))
print(four2)

[[1 2 3]
 [4 5 6]]
----------------------------------------------------------------------------------------------------
2666251661456
----------------------------------------------------------------------------------------------------
[[1 2]
 [3 4]
 [5 6]]
2666251661456
2666251661456
----------------------------------------------------------------------------------------------------
2666251661456
2669291337456
[[1 2 3]
 [4 5 6]]


In [30]:
# 将多维编程一维数组
five = four.reshape((6,), order='C')  # order='C'表示按行优先，'F'表示按列优先

six = four.flatten()  # 展平数组
print(five)
print(type(five))
print("-" * 100)
print(six)
print(type(six))
print("-" * 100)

seven = five.reshape(3, 2)
print(seven)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
----------------------------------------------------------------------------------------------------
[1 2 3 4 5 6]
<class 'numpy.ndarray'>
----------------------------------------------------------------------------------------------------
[[1 2]
 [3 4]
 [5 6]]


In [38]:
t = np.arange(24)
print(t)
print(f"shape: {t.shape}")
print(f"ndim: {t.ndim}")
print("-" * 100)
# 转换成二维
t1 = t.reshape((4, 6))
print(t1)
print(f"shape: {t1.shape}")
print(f"ndim: {t1.ndim}")
print("-" * 100)
# 转换成三维
# 最前面的是0轴，后面的是1轴，2轴
t2 = t1.reshape((2, 3, 4))
print(t2)
print(t2.shape)
print(t2.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
shape: (24,)
ndim: 1
----------------------------------------------------------------------------------------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
shape: (4, 6)
ndim: 2
----------------------------------------------------------------------------------------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


In [39]:
t3 = t.reshape((2, 3, 2, 2))
print(t3)
print(t3.shape)
print(t3.ndim)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
(2, 3, 2, 2)
4


# 4.5 数组转换为列表

In [40]:
# 将数组转换为列表 tolist
a = np.array([9, 12, 88, 45, 67])
print(type(a))
list_a = a.tolist()
print(type(list_a))
print(list_a)

<class 'numpy.ndarray'>
<class 'list'>
[9, 12, 88, 45, 67]


# Numpy的数据类型

In [43]:
import random

f = np.array([1, 2, 3, 4, 127], dtype=np.int8)  # 返回数组中每个元素的字节单位长度，dtype设置数据类型
print(f.itemsize)  # f.itemsize是int8的字节单位长度
# 获取数据类型
print(f.dtype)
print("-" * 100)
print(f)
f[4] += 1  # 修改数组元素
print(f[4])  # 发生溢出

1
int8
----------------------------------------------------------------------------------------------------
[  1   2   3   4 127]
-128


In [44]:
# 调整数据类型
f1 = f.astype(np.int64)  # 转换为int16类型
print(f1.dtype)
print(f1.itemsize)
print('-' * 100)

int64
8
----------------------------------------------------------------------------------------------------


In [45]:
random.random()  # 随机生成0-1之间的浮点数

0.23357588222447323

In [48]:
# 拓展随机生成小数
# 使用python语法，保留两位小数
print(round(random.random(), 2))  # 函数的round()方法可以保留小数位数
# np.float16 半精度
arr = np.array([random.random() for i in range(10)])
print(arr)
print(arr.dtype)
print(arr.itemsize)
# 去小数点后两位
print(np.round(arr, 2))  # 这里的round()跟python的round()方法不一样，是numpy的函数

0.77
[0.28505781 0.88727039 0.93185991 0.64802127 0.14368992 0.98394667
 0.25643595 0.61476085 0.8923262  0.16417947]
float64
8
[0.29 0.89 0.93 0.65 0.14 0.98 0.26 0.61 0.89 0.16]


# 数组和数的计算

In [49]:
# [1, 2, 3] + 5  # 列表和数的计算，会报错

TypeError: can only concatenate list (not "int") to list

In [52]:
# 由于numpy的广播机制在运算过程中，加减乘除的值被广播到所有元素的上面
t1 = np.arange(24).reshape((6, 4))
print(t1)
print("-" * 100)
t2 = t1.tolist()
print(t1 + 1)  # 数组和数的计算
print("-" * 100)
print(t1 * 2)
print("-" * 100)
print(t1 / 2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
----------------------------------------------------------------------------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
----------------------------------------------------------------------------------------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
----------------------------------------------------------------------------------------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


# ndarray与ndarray的运算

In [53]:
# 形状相同，才可以进行加减乘除
t1 = np.arange(24).reshape((6, 4))
t2 = np.arange(100, 124).reshape((6, 4))
print(t1)
print("-" * 100)
print(t2)
print("-" * 100)
print(t1 + t2)
print("-" * 100)
print(t1 * t2)  # 对应元素相乘

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
----------------------------------------------------------------------------------------------------
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
----------------------------------------------------------------------------------------------------
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
----------------------------------------------------------------------------------------------------
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


# shape不同，不能进行加减乘除

In [56]:
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(18).reshape((3, 6))
print(t1)
print("-" * 100)
print(t2)
print("-" * 100)
print(t1 - t2)  # 形状不同，不能进行加减乘除


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------------------------------------------------------------------------------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
----------------------------------------------------------------------------------------------------


ValueError: operands could not be broadcast together with shapes (4,6) (3,6) 

In [60]:
# 一维数组和二维数组运算时，一维的元素个数和列数相同
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((1, 6))
print(t2.shape)
print("-" * 100)
print(t1)
print("-" * 100)
print(t2)
print("-" * 100)
print(t1 - t2)  # 一维数组和二维数组运算时，一维的元素个数和列数相同
print("-" * 100)
print((t1 - t2).shape)

(1, 6)
----------------------------------------------------------------------------------------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------------------------------------------------------------------------------------------
[[0 1 2 3 4 5]]
----------------------------------------------------------------------------------------------------
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]
----------------------------------------------------------------------------------------------------
(4, 6)


In [61]:
# 随机三维数组
a = np.arange(24).reshape((2, 3, 4))
b = np.arange(12).reshape((1, 3, 4))
print(a - b)
# 结论：ndim要相同，可以某一个轴的size不同，但是其中一个ndarray必须对应的轴的size为1

[[[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[12 12 12 12]
  [12 12 12 12]
  [12 12 12 12]]]


# 练习轴

In [63]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("-" * 100)
print(np.sum(a, axis=0))  # 按列求和
print("-" * 100)
print(np.sum(a, axis=1))  # 按行求和
print("-" * 100)
print(np.sum(a))  # 所有元素求和


[[1 2 3]
 [4 5 6]]
----------------------------------------------------------------------------------------------------
[5 7 9]
----------------------------------------------------------------------------------------------------
[ 6 15]
----------------------------------------------------------------------------------------------------
21


In [64]:
a = np.arange(24).reshape((2, 3, 4))
b = np.sum(a, axis=0)
print(b.shape)
print("-" * 100)
c = np.sum(a, axis=1)
print(c.shape)
print("-" * 100)
d = np.sum(a, axis=2)
print(d.shape)
print("-" * 100)

(3, 4)
----------------------------------------------------------------------------------------------------
(2, 4)
----------------------------------------------------------------------------------------------------
(2, 3)
----------------------------------------------------------------------------------------------------


# 索引和切片

In [65]:
import numpy as np

a = np.arange(10)

# 如果只放置一个参数，如[2]，将返回与该索引对应的单个元素
print(a[0], a)
# 如果为[2:]，表示从该索引开始到结尾的所有元素
print(a[2:])

print(a[2:8:2])  # 切片是左闭右开的
print(a[::-1])  # 逆序

0 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6]
[9 8 7 6 5 4 3 2 1 0]


In [68]:
import numpy as np

t1 = np.arange(24).reshape((4, 6))
print(t1)
print("-" * 100)
print(t1[1])
print("-" * 100)
print(t1[1:])
print("-" * 100)
print(t1[1:3, :])  # 第一个维度是行，第二个维度是列，表示从1行到3行，所有列
print("-" * 100)
print(t1[[0, 2, 3]])  # 选中第0，2，3行，没有设置列，默认选中所有列

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------------------------------------------------------------------------------------------
[ 6  7  8  9 10 11]
----------------------------------------------------------------------------------------------------
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------------------------------------------------------------------------------------------
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
----------------------------------------------------------------------------------------------------
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [69]:
# 看列表
t2 = np.arange(24).reshape((4, 6)).tolist()
print(t2[[0, 2, 3]])  # 列表不能使用[[ ]]，只能使用[ ]

TypeError: list indices must be integers or slices, not list

In [74]:
print(t1[:, 1])
print("-" * 100)
print(t1[:, 1:])
print("-" * 100)
print(t1[:, [0, 2, 3]])
print("-" * 100)
print(t1[2, 3])
print("-" * 100)
print(t1[[0, 1, 1], [0, 1, 3]])  # 选中的三个元素分别是(0,0), (1,1), (1,3)，行列参数数量要相同

[ 1  7 13 19]
----------------------------------------------------------------------------------------------------
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
----------------------------------------------------------------------------------------------------
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
----------------------------------------------------------------------------------------------------
15
----------------------------------------------------------------------------------------------------
[0 7 9]


# 修改值

In [93]:
import numpy as np

t = np.arange(24).reshape((4, 6))
print(t)
print(id(t))
print("-" * 100)

# # 修改某一行的值
# t[1, :] = 0
# print(t)
# print("-" * 100)
#
# # 修改某一列的值
# t[:, 2] = 1000
# print(t)
# print("-" * 100)
#
# # 修改连续多行的值
# t[1:3, :] = 999
# print(t)
# print("-" * 100)
#
# # 修改多上多列，取第二行到第四行，第三列到第五列
# t[1:4, 2:5] = 888
# print(t)
# print("-" * 100)
#
# # 修改多个不相邻的点
# t[[0, 2], [1, 3]] = 777
# print(t)
# print("-" * 100)
#
# # 根据条件修改
# t[t > 777] = 666
# print(t)
# print("-" * 100)

# 使用逻辑判断修改
# t中大于11小于16的元素为True，其余为False，out=t表示将结果赋值给t
# np.logical_and(t > 11, t < 16, out=t)
# print(t)
# print("-" * 100)
#
# np.logical_or(t > 11, t < 16, out=t)
# print(t)
# print("-" * 100)
# t[(t > 11) & (t < 16)] = 0
# print(t)
# print("-" * 100)
# t[(t < 2) | (t > 6)] = 0
# print(t)
# print("-" * 100)
# t[~(t > 6)] = 0
# print(t)
# print("-" * 100)
# clip()方法把大于10的元素替换为10，小于0的元素替换为0
t.clip(0, 10, out=t)  # 将t中的值限制在0-10之间
print(t)
print(id(t))
print("-" * 100)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
2666257308912
----------------------------------------------------------------------------------------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
2666257308912
----------------------------------------------------------------------------------------------------


In [98]:
t = np.arange(24).reshape((4, 6))
print(t < 10)
t < 10

[[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False False False False False]
 [False False False False False False]]


array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [99]:
# python的三目运算符
a = 10
b = 15
c = a if a > b else b
print(c)

15


In [102]:
# 拓展
# 三目运算（np.where(condition, x, y)）满足条件(condition),输出x,否则输出y
score = np.array([[85, 90], [82, 81], [75, 81]])
print(score)
print("-" * 100)
result = np.where(score < 80, True, False)
print(result)
print("-" * 100)
score[result] = 0  # 将result为True的元素的位置赋值为0
print(score)
print("-" * 100)

[[85 90]
 [82 81]
 [75 81]]
----------------------------------------------------------------------------------------------------
[[False False]
 [False False]
 [ True False]]
----------------------------------------------------------------------------------------------------
[[85 90]
 [82 81]
 [ 0 81]]
----------------------------------------------------------------------------------------------------


# 数据的添加，删除与去重

In [116]:
# 1 numpy.append() 函数在数组的末尾添加元素。追加操作会分配新的内存，并复制原数组中的元素。
# 此外，输入数组的维度必须匹配否则会报错。
"""
参数说明：
axis有定义的时候，分别为0和1的时候（列数要相同）。当axis为1时，数组是加在右边（行数要相同）
"""
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.shape)
print("-" * 100)
b = np.append(a, [[7, 8, 9]], axis=0)  # axis=0时，列数要相同
print(b)
print("-" * 100)
c = np.append(a, [[7, 8, 9], [10, 11, 12]], axis=1)  # axis=1时，行数要相同
print(c)
print("-" * 100)

# print("向数组添加元素：")
# print(np.append(a, [7, 8, 9]))  # ndarray会被展平
# print("-" * 100)
# print(a)
# print("-" * 100)


[[1 2 3]
 [4 5 6]]
(2, 3)
----------------------------------------------------------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------------------------------------------------------------------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
----------------------------------------------------------------------------------------------------


In [117]:
b = np.array([[1, 2, 3]])
print(b.ndim)
print(b)
print("-" * 100)

2
[[1 2 3]]
----------------------------------------------------------------------------------------------------


In [119]:
print("沿轴0添加元素：")  # 往哪个轴添加元素，哪个轴的size就变大
print(np.append(a, [[7, 8, 9]], axis=0))
print("-" * 100)
print(a)
print("-" * 100)
print("沿轴1添加元素：")
print(np.append(a, [[5, 5, 5], [6, 6, 6]], axis=1))
print("-" * 100)
print(a)

沿轴0添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------------------------------------------------------------------
[[1 2 3]
 [4 5 6]]
----------------------------------------------------------------------------------------------------
沿轴1添加元素：
[[1 2 3 5 5 5]
 [4 5 6 6 6 6]]
----------------------------------------------------------------------------------------------------
[[1 2 3]
 [4 5 6]]


# numpy.insert()
# 函数在给定索引之前，沿给定轴在输入数组中插入值
# 函数在数组的指定位置插入元素。插入操作会分配新的内存，并复制原数组中的元素。

In [124]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print("第一个数组：")
print(a)
print("-" * 100)

print("未传递axis参数。在插入之前输入数组会被展平")
print(np.insert(a, 1, [11, 22]))
print("-" * 100)

print(np.insert(a, 1, [11, 12], axis=0))  # 哪个轴插入，哪个轴的size就变大
print("-" * 100)

print("沿轴0广播")
print(np.insert(a, 1, 11, axis=0))
print("-" * 100)
print("沿轴1广播")
print(np.insert(a, 1, 11, axis=1))

第一个数组：
[[1 2]
 [3 4]
 [5 6]]
----------------------------------------------------------------------------------------------------
未传递axis参数。在插入之前输入数组会被展平
[ 1 11 22  2  3  4  5  6]
----------------------------------------------------------------------------------------------------
[[ 1  2]
 [11 12]
 [ 3  4]
 [ 5  6]]
----------------------------------------------------------------------------------------------------
沿轴0广播
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
----------------------------------------------------------------------------------------------------
沿轴1广播
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [130]:
# numpy.delete() 函数删除数组中的元素。删除操作会分配新的内存，并复制原数组中的元素。
# 参数说明：
# 第一个参数：输入数组
# 第二个参数：索引，可以是整数，也可以是整数数组。如果是整数，表示删除指定位置的元素；如果是整数数组，表示删除指定位置的元素。
# 第三个参数：axis，表示删除的轴。

a = np.arange(24).reshape(4, 6)
print(a)
print("-" * 100)

print("未传递axis参数。在删除之前输入数组会被展平")
print(np.delete(a, 9))
print("-" * 100)

print("删除第一行")
print(np.delete(a, 1, axis=0))
print("-" * 100)

print("删除第零列")
print(np.delete(a, 0, axis=1))
print("-" * 100)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------------------------------------------------------------------------------------------
未传递axis参数。在删除之前输入数组会被展平
[ 0  1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
----------------------------------------------------------------------------------------------------
删除第一行
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------------------------------------------------------------------------------------------
删除第零列
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
----------------------------------------------------------------------------------------------------


In [137]:
# numpy.unique() 函数用于去除数组中的重复元素，并返回不重复元素组成的新数组。
# 参数说明：
# 第一个参数：输入数组
# 第二个参数：axis，表示去除重复元素的轴。
"""
arr:输入数组。
return_index：如果为True，返回索引数组，否则不返回。
return_inverse：如果为True，返回反向索引数组，否则不返回。
return_counts：如果为True，返回重复元素的计数，否则不返回。
"""

import numpy as np

a = np.array([1, 2, 3, 2, 4, 1, 5, 6, 5, 1, 2, 3, 4, 5, 6])
print("第一个数组：")
print(a)
print("-" * 100)

# 去除重复元素，输出的是有序数组
print("第一个数组的去重值：")
u = np.unique(a)
print(u)
print("-" * 100)

print("去重数组的索引数组：")
u, indices = np.unique(a, return_index=True)
print(u)
print(indices)
print("-" * 100)

print("去重前数组的元素在去重后数组的位置：")
u, indices = np.unique(a, return_inverse=True)
print(u)
print(indices)
print("-" * 100)



第一个数组：
[1 2 3 2 4 1 5 6 5 1 2 3 4 5 6]
----------------------------------------------------------------------------------------------------
第一个数组的去重值：
[1 2 3 4 5 6]
----------------------------------------------------------------------------------------------------
去重数组的索引数组：
[1 2 3 4 5 6]
[0 1 2 4 6 7]
----------------------------------------------------------------------------------------------------
去重前数组的元素在去重后数组的位置：
[1 2 3 4 5 6]
[0 1 2 1 3 0 4 5 4 0 1 2 3 4 5]
----------------------------------------------------------------------------------------------------


# numpy的数学计算

In [150]:
import numpy as np

score = np.array([[85, 90], [82, 81], [75, 81]])
print(score)
# 1 获取所有数据最大值
result = np.max(score)
print(result)
print("-" * 100)
# 2 获取某个轴上数据最大值，对应的轴就消失
result = np.max(score, axis=1)
print(result)
print("-" * 100)
# 3 获取最小值
result = np.min(score)
print(result)
print("-" * 100)
# 4 获取某一个轴上的数据最小值
result = np.min(score, axis=0)
print(result)
print("-" * 100)
# 5 数据的比较
result = np.maximum([-2, -1, 0, 1, 2], 0)  # 第一个参数中的每一个数与第二个参数中的数比较，返回较大的数
print(result)
result = np.minimum([-2, -1, 0, 1, 2], 0)  # 第一个参数中的每一个数与第二个参数中的数比较，返回较小的数
print(result)
print("-" * 100)
result = np.maximum([-2, -1, 5, 1, 2], [1, 2, 3, 4, 5])
print(result)
'''
通用函数：
numpy.sqrt(array)	平方根函数
numpy.exp(array)	e^array[i]的数组
numpy.abs/fabs(array)	计算绝对值
numpy.square(array)	计算各元素的平方 等于array	2
numpy.log/log10/log2(array)	计算各元素的各种对数
numpy.sign(array)	计算各元素正负号
numpy.isnan(array)	计算各元素是否为NaN
numpy.isinf(array)	计算各元素是否为NaN
numpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数
numpy.modf(array)	将array中值得整数和小数分离，作两个数组返回
numpy.ceil(array)	向上取整,也就是取比这个数大的整数
numpy.floor(array)	向下取整,也就是取比这个数小的整数
numpy.rint(array)	四舍五入
numpy.trunc(array)	向0取整
numpy.cos(array)	正弦值
numpy.sin(array)	余弦值
numpy.tan(array)	正切值

numpy.add(array1,array2)	元素级加法
numpy.subtract(array1,array2)	元素级减法
numpy.multiply(array1,array2)	元素级乘法
numpy.divide(array1,array2)	元素级除法 array1./array2
numpy.power(array1,array2)	元素级指数 array1.^array2
numpy.maximum/minimum(array1,aray2) 元素级最大值
numpy.fmax/fmin(array1,array2)	元素级最大值，忽略NaN
numpy.mod(array1,array2)	元素级求模
numpy.copysign(array1,array2)	将第二个数组中值得符号复制给第一个数组中值
numpy.greater/greater_equal/less/less_equal/equal/not_equal (array1,array2)
元素级比较运算，产生布尔数组
numpy.logical_end/logical_or/logic_xor(array1,array2)元素级的真值逻辑运算
'''

[[85 90]
 [82 81]
 [75 81]]
90
----------------------------------------------------------------------------------------------------
[90 82 81]
----------------------------------------------------------------------------------------------------
75
----------------------------------------------------------------------------------------------------
[75 81]
----------------------------------------------------------------------------------------------------
[0 0 0 1 2]
[-2 -1  0  0  0]
----------------------------------------------------------------------------------------------------
[1 2 5 4 5]


'\n通用函数：\nnumpy.sqrt(array)\t平方根函数\nnumpy.exp(array)\te^array[i]的数组\nnumpy.abs/fabs(array)\t计算绝对值\nnumpy.square(array)\t计算各元素的平方 等于array\t2\nnumpy.log/log10/log2(array)\t计算各元素的各种对数\nnumpy.sign(array)\t计算各元素正负号\nnumpy.isnan(array)\t计算各元素是否为NaN\nnumpy.isinf(array)\t计算各元素是否为NaN\nnumpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数\nnumpy.modf(array)\t将array中值得整数和小数分离，作两个数组返回\nnumpy.ceil(array)\t向上取整,也就是取比这个数大的整数\nnumpy.floor(array)\t向下取整,也就是取比这个数小的整数\nnumpy.rint(array)\t四舍五入\nnumpy.trunc(array)\t向0取整\nnumpy.cos(array)\t正弦值\nnumpy.sin(array)\t余弦值\nnumpy.tan(array)\t正切值\n\nnumpy.add(array1,array2)\t元素级加法\nnumpy.subtract(array1,array2)\t元素级减法\nnumpy.multiply(array1,array2)\t元素级乘法\nnumpy.divide(array1,array2)\t元素级除法 array1./array2\nnumpy.power(array1,array2)\t元素级指数 array1.^array2\nnumpy.maximum/minimum(array1,aray2) 元素级最大值\nnumpy.fmax/fmin(array1,array2)\t元素级最大值，忽略NaN\nnumpy.mod(array1,array2)\t元素级求模\nnumpy.copysign(array1,array2)\t将第二个数组中值得符号复制给第一个数组中值\nnumpy.greater/greater_equal/less/less_equal/eq

In [155]:
# 6 求平均值
result = np.mean(score)
print(result)
print("-" * 100)
result = np.mean(score, axis=0)
print(result)
print("-" * 100)

# 7 求前缀和
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("-" * 100)
print(arr.cumsum(axis=0))
"""
[1 2 3] -------> [1 2 3]
[4 5 6] -------> [1+4 2+5 3+6]
最终输出：
[[1 2 3]
 [5 7 9]]
"""

82.33333333333333
----------------------------------------------------------------------------------------------------
[80.66666667 84.        ]
----------------------------------------------------------------------------------------------------
[[1 2 3]
 [4 5 6]]
----------------------------------------------------------------------------------------------------
[[1 2 3]
 [5 7 9]]


'\n[1 2 3] -------> [1 2 3]\n[4 5 6] -------> [1+4 2+5 3+6]\n最终输出：\n[[1 2 3]\n [5 7 9]]\n'

In [159]:
# 8 argmin求最小值的索引
result = np.argmin(score, axis=0)  # axis=0表示沿着列求最小值，返回的是索引
res = np.min(score, axis=0)
print(score)
print(result)
print(res)
print("-" * 100)

# 9 求每一列的标准差（这里是总体标准差）
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值的差距较大
# 一个较小的标准差，代表数据集中数值分散较小，代表数据稳定，反之则代表数据不稳定。
result = np.std(score, axis=0)  # axis=0表示沿着列求标准差
print(result)
print("-" * 100)

# 10 求最大值与最小值的差
result = np.ptp(score, axis=None)  # 求最大值与最小值的差
print(result)

[[85 90]
 [82 81]
 [75 81]]
[2 1]
[75 81]
----------------------------------------------------------------------------------------------------
[4.18993503 4.24264069]
----------------------------------------------------------------------------------------------------
15


In [161]:
t = np.arange(30).reshape((10, 3))
print(t)
np.mean(t, axis=0)  # 求每一列的平均值

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


array([13.5, 14.5, 15.5])

# 数组的拼接

In [168]:
# 有时候我们需要将两个数据加起来一起研究分析，我们就可以将其进行拼接然后分析。
import numpy as np

# 1 根据轴连接的数组序列，concatenate()没有改变数组的维度
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[9, 10], [11, 12]])

# 要求a b两个数组的维度相同
print("沿着轴0连接两个数组：")
print(np.concatenate((a, b), axis=0))  # 写哪个轴哪个轴就发生变化
print("-" * 100)

print("沿着轴1连接三个数组：")
print(np.concatenate((a, b, c), axis=1))
print("-" * 100)

# 堆叠数组，stack()会改变数组的维度
print(np.stack((a, b, c), axis=0))
print(np.stack((a, b, c), axis=0).shape)
print("-" * 100)

# 根据轴进行堆叠，二维会变成三维
arrays = [np.arange(12).reshape(3, 4) for i in range(10)]
print(len(arrays))
print("沿轴0连接两个数组：")
result = np.stack(arrays, axis=0)  # 把列表中的数组元素沿着轴0进行堆叠
print(result)
print(result.shape)
print("-" * 100)


沿着轴0连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
----------------------------------------------------------------------------------------------------
沿着轴1连接三个数组：
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]
----------------------------------------------------------------------------------------------------
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)
----------------------------------------------------------------------------------------------------
10
沿轴0连接两个数组：
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
(10, 3, 4)


In [172]:
print("沿轴1连接两个数组：")
print(arrays[0])
print("-" * 100)
result = np.stack(arrays, axis=1)
print(result)
print(result.shape)

沿轴1连接两个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------------------------------------------------------------------------------------------
[[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]]]
(3, 10, 4)


In [174]:
print("沿轴2连接两个数组：这里的-1和2是等价的")
result = np.stack(arrays, axis=-1)
print(arrays[0])
print(result.shape)
print("-" * 100)
print(result)

沿轴2连接两个数组：这里的-1和2是等价的
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4, 10)
----------------------------------------------------------------------------------------------------
[[[ 0  0  0  0  0  0  0  0  0  0]
  [ 1  1  1  1  1  1  1  1  1  1]
  [ 2  2  2  2  2  2  2  2  2  2]
  [ 3  3  3  3  3  3  3  3  3  3]]

 [[ 4  4  4  4  4  4  4  4  4  4]
  [ 5  5  5  5  5  5  5  5  5  5]
  [ 6  6  6  6  6  6  6  6  6  6]
  [ 7  7  7  7  7  7  7  7  7  7]]

 [[ 8  8  8  8  8  8  8  8  8  8]
  [ 9  9  9  9  9  9  9  9  9  9]
  [10 10 10 10 10 10 10 10 10 10]
  [11 11 11 11 11 11 11 11 11 11]]]


In [176]:
# 3 .矩阵垂直拼接，vstack没有增加维度，类似于concatenate(axis=0) -- vertical
v1 = [[0, 1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10, 11]]
v2 = [[12, 13, 14, 15, 16, 17],
      [18, 19, 20, 21, 22, 23]]
result = np.vstack((v1, v2))
print(result)
print("-" * 100)

# 4 .矩阵水平拼接，hstack没有增加维度，类似于concatenate(axis=1) -- horizontal
h1 = [[0, 1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10, 11]]
h2 = [[12, 13, 14, 15, 16, 17],
      [18, 19, 20, 21, 22, 23]]
result = np.hstack((h1, h2))
print(result)
print("-" * 100)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------------------------------------------------------------------------------------------
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]
----------------------------------------------------------------------------------------------------


# 分割

In [178]:
# 1 将一个数组分割成多个子数组，split()
"""
参数说明：
arr：被分割的数组
indices_or_sections：整数或整数数组，表示分割的位置。
axis：整数，表示沿着哪个轴进行分割。
"""
import numpy as np

arr = np.arange(12).reshape(4, 3)
print(arr)
print("将数组分为三个大小相等的子数组：b是一个列表")
b = np.split(arr, 3, axis=1)  # 按那个轴，哪个轴就发生变化，参数3表示分割成三个子数组
print(b)
print(b[0].shape)
print("-" * 100)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
将数组分为三个大小相等的子数组：b是一个列表
[array([[0],
       [3],
       [6],
       [9]]), array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]])]
(4, 1)
----------------------------------------------------------------------------------------------------


In [181]:
b = np.split(arr, 4, axis=0)
print(b)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]


In [184]:
c = np.hsplit(arr, 3)  # 水平分割
print(c)
print(c[0].shape)
print("-" * 100)

[array([[0],
       [3],
       [6],
       [9]]), array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]])]
(4, 1)
----------------------------------------------------------------------------------------------------


In [185]:
d = np.random.random((2, 6))
print(d)

[[0.98318114 0.89709136 0.08864115 0.18456059 0.13476496 0.06782338]
 [0.01240818 0.80823119 0.76422416 0.72408189 0.96424977 0.0913505 ]]


In [186]:
harr = np.floor(10 * np.random.random((2, 6)))  # floor()函数向下取整
print(harr)

[[7. 6. 3. 8. 5. 9.]
 [2. 2. 7. 2. 8. 5.]]


In [187]:
a = np.arange(16).reshape(4, 4)

print("第一个数组：")
print(a)
print("-" * 100)

print("竖直分割：")
b = np.vsplit(a, 2)  # 竖直分割，分割成两个子数组
print(b)
print(b[0].shape)
print("-" * 100)

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----------------------------------------------------------------------------------------------------
竖直分割：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
(2, 4)
----------------------------------------------------------------------------------------------------


# numpy inf 与 nan

In [189]:
"""
C 语言中表示最大的正整数值是 0x7FFF FFFF，最小的负整数是 0x8000 0000。
查阅资料后，发现 inf 表示无穷大，需要使用 float(‘inf’) 函数来转化，那么对应的就有	float('-inf') 表示无穷小了。
这样你就可以使用任意数来判断和它的关系了。
那什么时候会出现inf呢？ 比如一个数字除以0，Python中会报错，但是numpy中会是一个inf或者-inf
另外还有 nan，这种写法在 pandans 中常见，表示缺失的数据，所以一般用 nan 来表示。任何与其做运算结果都是 nan
"""

import numpy as np

# nan 是not a number的缩写，表示非数字，在numpy中表示一个非数字值，可以用来表示缺失数据
# 创建一个nan和inf
a = np.nan
b = np.inf
c = -np.inf
print(a)  # 非数字
print(type(a))
print(b)  # 正无穷
print(type(b))
print(c)  # 负无穷
print(type(c))

nan
<class 'float'>
inf
<class 'float'>
-inf
<class 'float'>


In [192]:
# 并且 np.nan !=  np.nan 结果是True
# 所以我们可以使用这两个结合使用判断nan的个数:
print(np.nan == np.nan)
print(True == 1)
print(False == 0)
print(np.isnan(np.nan))  # 判断是否为nan

False
True
True
True


In [193]:
# 判断数组中nan的个数
t = np.arange(24, dtype=float).reshape(4, 6)

# 将三行四列的数改为nan
t[3, 4] = np.nan
print(t)


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. nan 23.]]


In [199]:
# 可以使用np.count_nonzero()函数来统计非零元素的个数
print(np.count_nonzero(t))  # 15
print("-" * 100)
print(t != t)  # 如果元素不等于nan，则为True，否则为False
print("-" * 100)
print(np.count_nonzero(t != t))  # 统计非nan元素的个数

23
----------------------------------------------------------------------------------------------------
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False  True False]]
----------------------------------------------------------------------------------------------------
1


In [202]:
# 将nan替换为0
# t[t != t] = 0
t[np.isnan(t)] = 0
print(t)


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [212]:
# --- 练习：处理数组中的nan
t = np.arange(24).reshape(4, 6).astype(float)

# 将数组中的一部分替换为nan
t[1, 2:4] = np.nan
t[2, 1:3] = np.nan
print(t)
print(t.shape[1])
print("-" * 100)
# 遍历每一列，然后判断每一列是否有nan
for i in range(t.shape[1]):
    # 获取当前列数据
    col = t[:, i]

    # 判断当前列的数据中是否含有nan
    # nan_num = np.count_nonzero(np.isnan(col))
    nan_num = np.count_nonzero(col != col)
    if nan_num != 0:
        # 将这一列不为nan的数据拿出来，并计算平均值
        col_no_nan = col[col == col]
        print(col_no_nan)
        # 将nan替换成这一列的平均值
        col[np.isnan(col)] = np.mean(col_no_nan)
print("-" * 100)
print(t)
print("-" * 100)
print(id(t))

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7. nan nan 10. 11.]
 [12. nan nan 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
6
----------------------------------------------------------------------------------------------------
[ 1.  7. 19.]
[ 2. 20.]
[ 3. 15. 21.]
----------------------------------------------------------------------------------------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7. 11. 13. 10. 11.]
 [12.  9. 11. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
----------------------------------------------------------------------------------------------------
2665045209424


In [213]:
print(np.inf == np.inf)


True


In [214]:
# np.nan和任何数据运算的结果都是nan
t = np.arange(24).reshape(4, 6).astype(float)

# 将数组中的一部分替换为nan
t[1, 3:] = np.nan
t1 = np.arange(24).reshape(4, 6).astype(float)
t + t1

array([[ 0.,  2.,  4.,  6.,  8., 10.],
       [12., 14., 16., nan, nan, nan],
       [24., 26., 28., 30., 32., 34.],
       [36., 38., 40., 42., 44., 46.]])

In [215]:
arr = np.array([-1, 0])
print(arr)
print(arr[0] / arr[1])

[-1  0]
-inf


C:\Users\Administrator\AppData\Local\Temp\ipykernel_13092\3781747794.py:3: RuntimeWarning: divide by zero encountered in long_scalars
  print(arr[0] / arr[1])


In [216]:
np.nan + np.inf

nan

# 转置和轴滚动

In [218]:
# 对换数组的维度
import numpy as np

a = np.arange(12).reshape(3, 4)
print("原数组：")
print(a)
print("-" * 100)

print("对换数组：")
print(np.transpose(a))  # 转置
print(a)
print("-" * 100)

# 与transpose函数一致
print("原数组：")
print(a)
print("-" * 100)

print("转置后数组：")
print(a.T)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------------------------------------------------------------------------------------------
对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------------------------------------------------------------------------------------------
原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------------------------------------------------------------------------------------------
转置后数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [220]:
# 函数用于交换数组的两个轴
t1 = np.arange(24).reshape(4, 6)
ret = t1.swapaxes(0, 1)  # 交换第0轴和第1轴
print(t1)
print("-" * 100)
print(ret)
print(ret.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------------------------------------------------------------------------------------------
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
(6, 4)


In [223]:
t3 = np.arange(60).reshape(3, 4, 5)
print(t3.shape)
print("-" * 100)
t3 = np.swapaxes(t3, 1, 2)  # 交换第1轴和第2轴
print(t3.shape)
# print(t3)

(3, 4, 5)
----------------------------------------------------------------------------------------------------
(3, 5, 4)


In [224]:
# 数组的轴滚动，swapaxes()每次只能交换两个轴，没有rollaxis方便，默认情况下轴滚动最前面
a = np.ones((3, 4, 5, 6))
np.rollaxis(a, 3, 1).shape  # 将第3轴放到第1轴之前

(3, 6, 4, 5)

In [225]:
# 数据拷贝，copy和赋值的区别
b = np.array([[1, 2, 3], [1, 2, 3]])
a = b.copy()  # 数组的拷贝
a

array([[1, 2, 3],
       [1, 2, 3]])

In [227]:
b[0, 0] = 3
print(b)
a

[[3 2 3]
 [1 2 3]]


array([[1, 2, 3],
       [1, 2, 3]])

In [228]:
# 随机数的生成
arr = np.random.rand(2, 3, 4)  # 产生2*3*4的随机数组
print(arr)

[[[0.26502441 0.6743974  0.81837116 0.48061142]
  [0.10043376 0.11115348 0.71489483 0.57615409]
  [0.27897653 0.02570505 0.645723   0.95357601]]

 [[0.11251538 0.85221296 0.97918489 0.21947207]
  [0.9856699  0.85432466 0.21261745 0.34449119]
  [0.11168219 0.04649874 0.23867934 0.42897174]]]
